### ISSUE TITLE
postcss-initial's replace option

### ISSUE THREAD

**Issue by maximkoretskiy** [DmitryAuine/postcss-initial-fixer#1]
`postcss-initial` has option `replace` which do all work your plugin do) 

https://github.com/maximkoretskiy/postcss-initial#replace

**Comment by DmitryAuine** [comment]
Thanks! This plugin was created before that issue :))

**Comment by maximkoretskiy** [comment]
Before that https://github.com/maximkoretskiy/postcss-initial/issues/9 or before this https://github.com/maximkoretskiy/postcss-initial/issues/13 )?

**Comment by DmitryAuine** [comment]
Second one :))
